config/routes.rb
Rails.application.routes.draw do
 
 root 'search#index'
 get '/search' =>'search#index'
 get '/csv' =>'search#csv'
end

app/models/search.rb
class Search

	def by(intent,options)
		params = ""
		options.each do |v,k|
            params += "#{v}=#{k}&"
        end
        response = HTTParty.get(URI.encode("https://api.foursquare.com/v2/venues/explore?intent=#{intent}&#{params}limit=50&client_id=DGYOAJXYGFIC5Y44Z5JA5HEU10CXPDF0UKQEZQA4JMPIOVDZ&client_secret=SD1WOKW14QOLFF1PWHJ2HGE3DDZS1OW40HRULDCOXAGXDFGE&v=20140806"))
        # puts response.body
        JSON.parse(response.body)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
before_action :clean_params
	def index
		unless @params == {}
			api_call
		end
	end
	def csv
		respond_to do |format|
		   	format.csv do
			    headers['Content-Disposition'] = "attachment; filename=\"Restaruant-List.csv\""
			    headers['Content-Type'] ||= 'text/csv'
			end
		end
	end
	def api_call
		@search = Search.new
		@response = @search.by("browse",@params)
		@meta = @response['meta']['code']
		@results = @response['response']['groups'][0]['items']
		if @results.length == 50
			do_loop = true
			@params[:offset] = 50
			puts "&&&&&&#{@params}&&&&&&&"
			while do_loop == true
				@response= @search.by("browse",@params)
				puts "-------#{@response['response']['groups'][0]['items'].length	}-------"
				@meta = @response['meta']['code']
				new_results = @response['response']['groups'][0]['items']
				@results += new_results

				if new_results.length != 50
					do_loop = false
					puts "++++++++#{@results.length}++++++++"
				else
					@params[:offset] = @params[:offset].to_i + 50
				end
			end
		end
	end

	def clean_params
		@params = params.permit(:ll,:radius,:limit,:categoryId,:format,:offset,clean_params: {})
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantScrappr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/csv.csv.erb
<% search = Search.new %>
<% response = search.by("browse",@params) %>
<% meta = response['meta']['code'] %>
<% unless meta == 400 || response == nil || response.length == 0 %>
<% results = response['response']['groups'][0]['items'] %>
<% headers = [
				'ID',
				'Name',
				'Phone',
				'Twitter',
				'Lat&lng', 
				'Address',
				'Zip Code', 
				'City',
				'State',
				'Categorie IDs',
				'Categories',
				'Check Ins',
				'User Count',
				'Restaurant Website',
				'Foursquared Website'
				] %>
<%= CSV.generate_line headers %>

<% results.each do |venue| %>
	<% lat_and_lng = "#{venue['location']['lat']} #{venue['location']['lng']}"%>
	<%= CSV.generate_line([
		venue['venue']['id'], 
		venue['venue']['name'],
		venue['venue']['contact']['formattedPhone'],
		venue['venue']['contact']['twitter'],
		lat_and_lng,
		venue['venue']['location']['address'],
		venue['venue']['location']['postalCode'],
		venue['venue']['location']['city'],
		venue['venue']['location']['state'],
		venue['venue']['categories'][0]['id'],
		venue['venue']['categories'][0]['shortName'],
		venue['venue']['stats']['checkinsCount'],
		venue['venue']['stats']['usersCount'],
		venue['venue']['url']
		]) %>
<% end %>
<%end%>

app/views/search/index.html.erb
<%= form_tag("/search", method: "get") do %>
<%= label_tag(:ll, "Lat and long") %>
<%= text_field_tag(:ll,params[:ll] ) %>
<%= label_tag(:radius, "Radius") %>
<%= text_field_tag(:radius,params[:radius]) %>
<%= label_tag(:categoryId, "Category") %>
<%= select_tag(:categoryId, options_for_select([
	['Food','4d4b7105d754a06374d81259'],
	['Restaurant','4bf58dd8d48988d1c4941735'],
	['----------------------','4d4b7105d754a06374d81259'],
	['American Restaurant','4bf58dd8d48988d14e941735'],
	['Asian Restaurant','4bf58dd8d48988d142941735'],
	['Brazilian Restaurant','4bf58dd8d48988d16b941735'],
	['Buffet','52e81612bcbc57f1066b79f4'],
	['Burger Joint','4bf58dd8d48988d16c941735'],
	['Caribbean Restaurant','4bf58dd8d48988d144941735'],
	['Dessert Shop', '4bf58dd8d48988d1d0941735'],
	['Diner','4bf58dd8d48988d147941735'],
	['Eastern European Restaurant','4bf58dd8d48988d109941735'],
	['Fast Food Restaurant','4bf58dd8d48988d16e941735'],
	['Food Court','4bf58dd8d48988d120951735'],
	['Food Truck','4bf58dd8d48988d1cb941735'],
	['Fried Chicken Joint','4d4ae6fc7a7b7dea34424761'],
	['Greek Restaurant','4bf58dd8d48988d10e941735'],
	['Hot Dog Joint','4bf58dd8d48988d16f941735'],
	['Indian Restaurant','4bf58dd8d48988d10f941735'],
	['Indonesian Restaurant','4deefc054765f83613cdba6f'],
	['Italian Restaurant','4bf58dd8d48988d110941735'],
	['Latin American Restaurant','4bf58dd8d48988d1be941735'],
	['Mediterranean Restaurant','4bf58dd8d48988d1c0941735'],
	['Mexican Restaurant','4bf58dd8d48988d1c1941735'],
	['Middle Eastern Restaurant','4bf58dd8d48988d115941735'],
	['Pizza Place','4bf58dd8d48988d1ca941735'],
	['Russian Restaurant','5293a7563cf9994f4e043a44'],
	['Sandwich Place','4bf58dd8d48988d1c5941735'],
	['Seafood Restaurant','4bf58dd8d48988d1ce941735'],
	['South American Restaurant','4bf58dd8d48988d1cd941735'],
	['Southern / Soul Food Restaurant','4bf58dd8d48988d14f941735'],
	['Spanish Restaurant','4bf58dd8d48988d150941735'],
	['Steakhouse','4bf58dd8d48988d1cc941735'],
	['Turkish Restaurant','4f04af1f2fb6e1c99f3db0bb'],
	['Ukrainian Restaurant','52e928d0bcbc57f1066b7e96']])) %>
<%= submit_tag("Search") %>
<% end %>
	<% unless @meta == 400 || @response == nil || @response.length == 0 %>
	<%= link_to 'Download CSV list', csv_path(format: :csv, clean_params: @params) %>    
	<table border="1" class="table table-striped">

		<h2>Results: <%= @results.length%></h2>
		<br/>

		<tr id="header">
			<td>
				ID
			</td>
			<td>
				Name
			</td>
			<td>
				phone
			</td>
			<td>
				twitter
			</td>
			<td>
				lat and lng
			</td>
			<td>
				address
			</td>
			<td>
				zip code
			</td>
			<td>
				city
			</td>
			<td>
				state
			</td>
			<td>
				categorie ids
			</td>
			<td>
				categories
			</td>
			<td>
				checkins
			</td>
			<td>
				user count
			</td>
			<td>
				restaurant website
			</td>
			<td>
				foursquared website
			</td>
		</tr>

		<% @results.each do |venue| %>
		<tr>
			<td>
				<%= venue['venue']['id'] %>
			</td>
			<td>
				<%= venue['venue']['name'] %>
			</td>
			<td>
				<%= venue['venue']['contact']['formattedPhone'] %>
			</td>
			<td>
				<%= venue['venue']['contact']['twitter'] %>
			</td>
			<td>
				<%= "#{venue['venue']['location']['lat']}, #{venue['venue']['location']['lng']}" %>
			</td>
			<td>
				<%= venue['venue']['location']['address'] %>
			</td>
			<td>
				<%= venue['venue']['location']['postalCode'] %>
			</td>
			<td>
				<%= venue['venue']['location']['city'] %>
			</td>
			<td>
				<%= venue['venue']['location']['state'] %>
			</td>
			<td>
				<% venue['venue']['categories'].each do |venue| %>
				<%= "#{venue['id']} " %>
				<% end %>
			</td>
			<td>
				<% venue['venue']['categories'].each do |venue| %>
				<%= "#{venue['shortName']} " %>
				<% end %>
			</td>
			<td>
				<%= venue['venue']['stats']['checkinsCount'] %>
			</td>
			<td>
				<%= venue['venue']['stats']['usersCount'] %>
			</td>
			<td>
				<a href=<%= venue['venue']['url']%>><%= venue['venue']['url']%></a>
			</td>
			<td>
				<% if venue['venue']['hasMenu'] == true%>
				<a href=<%= venue['venue']['menu']['url']%>><%= venue['venue']['menu']['url']%></a>
				<% else %>
				none
				<% end %>
			</td>
		</tr>
		<% end %>

	</table>
<%else%>
<h2>No Results</h2>
<%	end%>